[package]
name = "intelligent-dashboard-builder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "intelligent_dashboard_builder"
path = "src/lib.rs"

[[bin]]
name = "intelligent_dashboard_builder_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
