[package]
name = "security-console-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lib]
name = "security_console_ui"
path = "src/lib.rs"

[[bin]]
name = "security_console_ui_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


