[package]
name = "data-table-component"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "data_table_component"
path = "src/lib.rs"

[[bin]]
name = "data_table_component_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
