[package]
name = "docker-registry-integration"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "docker_registry_integration"
path = "src/lib.rs"

[[bin]]
name = "docker_registry_integration_cli"
path = "src/bin/cli.rs"
test = false



