[package]
name = "docker-network-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "docker_network_manager"
path = "src/lib.rs"

[[bin]]
name = "docker_network_manager_cli"
path = "src/bin/cli.rs"
test = false



