[package]
name = "docker-volume-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "docker_volume_manager"
path = "src/lib.rs"

[[bin]]
name = "docker_volume_manager_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


