[package]
name = "docker-image-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "docker_image_manager"
path = "src/lib.rs"

[[bin]]
name = "docker_image_manager_cli"
path = "src/bin/cli.rs"
test = false



