[package]
name = "documentation-viewer-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "documentation_viewer_ui"
path = "src/lib.rs"

[[bin]]
name = "documentation_viewer_ui_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
