[package]
name = "infinite-scroll-component"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "infinite_scroll_component"
path = "src/lib.rs"

[[bin]]
name = "infinite_scroll_component_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
