[package]
name = "audit-logging-platform"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lib]
name = "audit_logging_platform"
path = "src/lib.rs"

[[bin]]
name = "audit_logging_platform_cli"
path = "src/bin/cli.rs"


