// OmniCC Language Registry — 1000+ programming languages
// Organized by family. Explicit entries for top ~250 languages;
// family defaults cover the remaining 750+.

import { LanguageDef, LanguageFamily } from './ULIR';

// ─── Registry data ────────────────────────────────────────────────────────────

const LANGUAGES: LanguageDef[] = [

    // ── C-Family ──────────────────────────────────────────────────────────────
    { id: 'c',           name: 'C',           aliases: ['ansi-c', 'iso-c'],     extensions: ['.c','.h'],                  family: 'c-family',      paradigms: ['imperative', 'declarative'],             typing: 'static-weak',   memory: 'manual',   year: 1972, popularity: 9, color: '#555555', description: 'The lingua franca of systems programming', keywords: ['#include','printf','malloc','typedef','struct'], shebang: undefined, comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['pointers','manual-memory','preprocessor'] },
    { id: 'cpp',         name: 'C++',         aliases: ['cxx','c-plus-plus'],   extensions: ['.cpp','.cxx','.cc','.hpp'], family: 'c-family',      paradigms: ['imperative', 'oop', 'functional'],       typing: 'static-weak',   memory: 'manual',   year: 1985, popularity: 9, color: '#f34b7d', description: 'Systems language with OOP and templates',   keywords: ['namespace','template','class','virtual','#include<iostream>'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['templates','raii','stl','lambdas'] },
    { id: 'csharp',      name: 'C#',          aliases: ['cs','c-sharp'],        extensions: ['.cs'],                      family: 'c-family',      paradigms: ['imperative', 'oop', 'functional'],       typing: 'static-strong', memory: 'managed',  year: 2000, popularity: 8, color: '#178600', description: 'Microsoft\'s elegant managed language',    keywords: ['using','namespace','class','var','async','await','LINQ'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['linq','async-await','nullable','records','pattern-matching'] },
    { id: 'java',        name: 'Java',        aliases: ['jvm'],                 extensions: ['.java'],                    family: 'c-family',      paradigms: ['imperative', 'oop'],                     typing: 'static-strong', memory: 'gc',       year: 1995, popularity: 9, color: '#b07219', description: 'Write once, run anywhere JVM language',    keywords: ['public','static','void','class','import','extends','implements'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['generics','streams','lambdas','records','sealed'] },
    { id: 'javascript',  name: 'JavaScript',  aliases: ['js','ecmascript','es'],extensions: ['.js','.mjs','.cjs'],        family: 'c-family',      paradigms: ['imperative', 'oop', 'functional', 'event-driven'], typing: 'dynamic-weak', memory: 'gc', year: 1995, popularity: 10, color: '#f1e05a', description: 'The language of the web', keywords: ['function','const','let','var','=>','require','module.exports','document'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['prototypes','closures','promises','async-await','esmodules'] },
    { id: 'typescript',  name: 'TypeScript',  aliases: ['ts'],                  extensions: ['.ts','.tsx'],               family: 'c-family',      paradigms: ['imperative', 'oop', 'functional'],       typing: 'gradual',       memory: 'gc',       year: 2012, popularity: 9, color: '#2b7489', description: 'JavaScript with types by Microsoft',       keywords: ['interface','type','enum','as','implements','readonly','namespace'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['generics','decorators','mapped-types','conditional-types','template-literal-types'] },
    { id: 'kotlin',      name: 'Kotlin',      aliases: ['kt'],                  extensions: ['.kt','.kts'],               family: 'c-family',      paradigms: ['imperative', 'oop', 'functional'],       typing: 'static-strong', memory: 'gc',       year: 2011, popularity: 7, color: '#A97BFF', description: 'Modern JVM language by JetBrains',         keywords: ['fun','val','var','data class','object','companion','coroutines'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['null-safety','coroutines','data-classes','extension-functions','sealed'] },
    { id: 'swift',       name: 'Swift',       aliases: [],                      extensions: ['.swift'],                   family: 'c-family',      paradigms: ['imperative', 'oop', 'functional'],       typing: 'static-strong', memory: 'arc',      year: 2014, popularity: 7, color: '#ffac45', description: 'Apple\'s modern systems & app language',   keywords: ['func','var','let','guard','optional','protocol','extension','@objc'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['optionals','protocols','value-types','concurrency','result-builders'] },
    { id: 'go',          name: 'Go',          aliases: ['golang'],              extensions: ['.go'],                      family: 'c-family',      paradigms: ['imperative', 'concurrent'],              typing: 'static-strong', memory: 'gc',       year: 2009, popularity: 8, color: '#00ADD8', description: 'Google\'s fast, concise systems language',  keywords: ['package','import','func','goroutine','chan','defer','go ','interface{'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['goroutines','channels','interfaces','garbage-collection','modules'] },
    { id: 'dart',        name: 'Dart',        aliases: [],                      extensions: ['.dart'],                    family: 'c-family',      paradigms: ['imperative', 'oop', 'functional'],       typing: 'static-strong', memory: 'gc',       year: 2011, popularity: 6, color: '#00B4AB', description: 'Google\'s language for Flutter UIs',        keywords: ['void','class','extends','implements','mixin','final','late','flutter'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['null-safety','generics','async-await','streams','isolates'] },
    { id: 'scala',       name: 'Scala',       aliases: [],                      extensions: ['.scala','.sc'],             family: 'c-family',      paradigms: ['oop', 'functional'],                     typing: 'static-strong', memory: 'gc',       year: 2004, popularity: 6, color: '#c22d40', description: 'Scalable JVM language blending OOP+FP',    keywords: ['trait','case class','object','def','val','implicit','match','for comprehension'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['pattern-matching','implicits','case-classes','akka','spark'] },
    { id: 'objc',        name: 'Objective-C', aliases: ['obj-c'],               extensions: ['.m','.mm'],                 family: 'c-family',      paradigms: ['imperative', 'oop'],                     typing: 'static-weak',   memory: 'arc',      year: 1984, popularity: 5, color: '#438eff', description: 'Apple\'s C superset for macOS/iOS',        keywords: ['@interface','@implementation','@property','NSObject','#import'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['messaging','categories','protocols','blocks'] },
    { id: 'java-groovy', name: 'Groovy',      aliases: ['groovy'],              extensions: ['.groovy','.gvy'],           family: 'c-family',      paradigms: ['imperative', 'oop', 'functional'],       typing: 'gradual',       memory: 'gc',       year: 2003, popularity: 5, color: '#4298b8', description: 'Dynamic JVM scripting and build language',  keywords: ['def','println','@Grab','Closure','@groovy'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['closures','dynamic-typing','dsl','scripting'] },
    { id: 'haxe',        name: 'Haxe',        aliases: [],                      extensions: ['.hx'],                      family: 'c-family',      paradigms: ['imperative', 'oop', 'functional'],       typing: 'static-strong', memory: 'gc',       year: 2005, popularity: 4, color: '#df7900', description: 'Cross-platform toolkit compiling to many targets', keywords: ['class','interface','enum','macro','@:native'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['multi-target','macros','generics','pattern-matching'] },
    { id: 'actionscript',name: 'ActionScript',aliases: ['as3'],                 extensions: ['.as'],                      family: 'c-family',      paradigms: ['imperative', 'oop', 'event-driven'],     typing: 'static-strong', memory: 'gc',       year: 1998, popularity: 3, color: '#882B0F', description: 'Flash/Flex scripting language (ECMAScript derivative)', keywords: ['package','import','public class','var:','MovieClip'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['events','display-list','flex'] },
    { id: 'd',           name: 'D',           aliases: ['dlang'],               extensions: ['.d'],                       family: 'c-family',      paradigms: ['imperative', 'oop', 'functional', 'meta'], typing: 'static-strong', memory: 'gc',     year: 2001, popularity: 4, color: '#ba595e', description: 'Systems language combining C++ power with modern design', keywords: ['module','import','auto','mixin','template','__traits','pragma'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['templates','mixins','contracts','ranges','ctfe'] },
    { id: 'vala',        name: 'Vala',        aliases: [],                      extensions: ['.vala'],                    family: 'c-family',      paradigms: ['imperative', 'oop'],                     typing: 'static-strong', memory: 'gc',       year: 2006, popularity: 2, color: '#7239B3', description: 'GObject-based C# like language for GNOME',  keywords: ['namespace','class','using','signal','async','GLib'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['gobject','signals','properties','asynchronous'] },
    { id: 'carbon',      name: 'Carbon',      aliases: [],                      extensions: ['.carbon'],                  family: 'c-family',      paradigms: ['imperative', 'oop'],                     typing: 'static-strong', memory: 'manual',   year: 2022, popularity: 3, color: '#1a1a1a', description: 'Google\'s experimental C++ successor',     keywords: ['fn','var','let','class','interface','match','api'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['interop-with-c++','safety','generics'] },
    { id: 'chapel',      name: 'Chapel',      aliases: [],                      extensions: ['.chpl'],                    family: 'c-family',      paradigms: ['imperative', 'concurrent', 'dataflow'],  typing: 'static-strong', memory: 'gc',       year: 2009, popularity: 2, color: '#8dc63f', description: 'Parallel programming language by Cray',    keywords: ['proc','domain','coforall','on','locale','atomic'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['parallel','distributed','domains','locales'] },
    { id: 'cython',      name: 'Cython',      aliases: [],                      extensions: ['.pyx','.pxd'],              family: 'c-family',      paradigms: ['imperative', 'oop'],                     typing: 'gradual',       memory: 'manual',   year: 2007, popularity: 4, color: '#fedf5b', description: 'Superset of Python compiled to C',        keywords: ['cdef','cpdef','pyx','ctypedef','nogil','cimport'], comment: { line: '#', blockStart: '"""', blockEnd: '"""' }, indentStyle: 'indent', features: ['c-interop','static-types','extensions','nogil'] },

    // ── Python-family ─────────────────────────────────────────────────────────
    { id: 'python',      name: 'Python',      aliases: ['py','python3'],        extensions: ['.py','.pyw','.pyi'],        family: 'python-family', paradigms: ['imperative', 'oop', 'functional'],       typing: 'dynamic-strong',memory: 'gc',       year: 1991, popularity: 10, color: '#3572A5', description: 'Batteries-included readability-first language', keywords: ['def','class','import','from','print','if __name__'], shebang: '#!/usr/bin/env python3', comment: { line: '#', blockStart: '"""', blockEnd: '"""' }, indentStyle: 'indent', features: ['comprehensions','decorators','generators','dataclasses','type-hints'] },
    { id: 'ruby',        name: 'Ruby',        aliases: ['rb'],                  extensions: ['.rb','.rake','.gemspec'],   family: 'python-family', paradigms: ['imperative', 'oop', 'functional'],       typing: 'dynamic-strong',memory: 'gc',       year: 1995, popularity: 7, color: '#701516', description: 'Elegant, expressive OOP scripting language', keywords: ['def','end','class','module','attr_accessor','do |','puts','require'], shebang: '#!/usr/bin/env ruby', comment: { line: '#', blockStart: '=begin', blockEnd: '=end' }, indentStyle: 'begin-end', features: ['blocks','mixins','metaprogramming','rails','symbols'] },
    { id: 'lua',         name: 'Lua',         aliases: [],                      extensions: ['.lua'],                     family: 'python-family', paradigms: ['imperative', 'functional'],              typing: 'dynamic-strong',memory: 'gc',       year: 1993, popularity: 6, color: '#000080', description: 'Lightweight, embeddable scripting language', keywords: ['function','local','do','then','end','require','table','ipairs'], comment: { line: '--', blockStart: '--[[', blockEnd: ']]' }, indentStyle: 'begin-end', features: ['tables','metatables','coroutines','embedding','no-integers'] },
    { id: 'perl',        name: 'Perl',        aliases: ['pl'],                  extensions: ['.pl','.pm','.pod'],         family: 'python-family', paradigms: ['imperative', 'functional'],              typing: 'dynamic-weak',  memory: 'gc',       year: 1987, popularity: 5, color: '#0298c3', description: 'Practical extraction and report language',  keywords: ['my','sub','use strict','use warnings','$_','@_','%hash'], shebang: '#!/usr/bin/perl', comment: { line: '#', blockStart: '=pod', blockEnd: '=cut' }, indentStyle: 'braces', features: ['regex','references','modules','cpan'] },
    { id: 'php',         name: 'PHP',         aliases: [],                      extensions: ['.php','.phtml'],            family: 'python-family', paradigms: ['imperative', 'oop', 'functional'],       typing: 'gradual',       memory: 'gc',       year: 1994, popularity: 7, color: '#4F5D95', description: 'Server-side web scripting language',        keywords: ['<?php','echo','$','function','class','namespace','use','require_once'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['web-integration','psr','composer','types','attributes'] },
    { id: 'crystal',     name: 'Crystal',     aliases: [],                      extensions: ['.cr'],                      family: 'python-family', paradigms: ['imperative', 'oop', 'functional'],       typing: 'static-strong', memory: 'gc',       year: 2014, popularity: 4, color: '#000100', description: 'Ruby syntax with static types and C performance', keywords: ['def','end','class','module','require','annotation','macro'], comment: { line: '#', blockStart: '=begin', blockEnd: '=end' }, indentStyle: 'begin-end', features: ['concurrency','fibers','c-bindings','macros','nil-safety'] },
    { id: 'nim',         name: 'Nim',         aliases: [],                      extensions: ['.nim'],                     family: 'python-family', paradigms: ['imperative', 'functional', 'meta'],      typing: 'static-strong', memory: 'gc',       year: 2008, popularity: 4, color: '#ffe953', description: 'Efficient, expressive systems language with Pythonic syntax', keywords: ['proc','var','let','const','import','type','template','macro'], comment: { line: '#', blockStart: '#[', blockEnd: ']#' }, indentStyle: 'indent', features: ['templates','macros','zero-cost','gc-choices','ffi'] },
    { id: 'coffee',      name: 'CoffeeScript',aliases: ['coffeescript'],        extensions: ['.coffee'],                  family: 'python-family', paradigms: ['imperative', 'functional'],              typing: 'dynamic-weak',  memory: 'gc',       year: 2009, popularity: 3, color: '#244776', description: 'Little language that compiles to JavaScript', keywords: ['->'  ,'class','extends','@','unless','until','->'], comment: { line: '#', blockStart: '###', blockEnd: '###' }, indentStyle: 'indent', features: ['comprehensions','destructuring','compile-to-js'] },
    { id: 'elixir',      name: 'Elixir',      aliases: [],                      extensions: ['.ex','.exs'],               family: 'python-family', paradigms: ['functional', 'concurrent'],              typing: 'dynamic-strong',memory: 'gc',       year: 2012, popularity: 6, color: '#6e4a7e', description: 'Functional, concurrent language on Erlang VM', keywords: ['defmodule','def','defp','|>','case','with','use','require','alias'], comment: { line: '#' }, indentStyle: 'begin-end', features: ['pattern-matching','metaprogramming','phoenix','otp','macros'] },
    { id: 'julia',       name: 'Julia',       aliases: [],                      extensions: ['.jl'],                      family: 'ml-scientific',  paradigms: ['imperative', 'functional', 'array'],    typing: 'dynamic-strong',memory: 'gc',       year: 2012, popularity: 5, color: '#a270ba', description: 'High-performance scientific computing language', keywords: ['function','end','module','struct','const','@','::','begin'], comment: { line: '#', blockStart: '#=', blockEnd: '=#' }, indentStyle: 'begin-end', features: ['multiple-dispatch','metaprogramming','macros','simd','distributed'] },
    { id: 'r',           name: 'R',           aliases: [],                      extensions: ['.r','.R','.Rmd'],           family: 'ml-scientific',  paradigms: ['imperative', 'functional', 'array'],    typing: 'dynamic-strong',memory: 'gc',       year: 1993, popularity: 6, color: '#198CE7', description: 'Statistical computing and graphics language', keywords: ['library','function','if','else','for','<-','data.frame','ggplot'], shebang: '#!/usr/bin/env Rscript', comment: { line: '#' }, indentStyle: 'braces', features: ['vectorized','data-frames','ggplot2','cran','tidyverse'] },
    { id: 'matlab',      name: 'MATLAB',      aliases: ['octave'],              extensions: ['.m'],                       family: 'ml-scientific',  paradigms: ['imperative', 'array'],                  typing: 'dynamic-weak',  memory: 'gc',       year: 1984, popularity: 5, color: '#bb92ac', description: 'Numerical computing and matrix manipulation', keywords: ['function','end','for','while','matrix','plot','fprintf','clc'], comment: { line: '%', blockStart: '%{', blockEnd: '%}' }, indentStyle: 'begin-end', features: ['matrices','plotting','toolboxes','simulink'] },
    { id: 'apl',         name: 'APL',         aliases: [],                      extensions: ['.apl','.apln','.aplc'],     family: 'ml-scientific',  paradigms: ['array', 'functional'],                  typing: 'dynamic-strong',memory: 'gc',       year: 1966, popularity: 2, color: '#5A8164', description: 'Array programming language with symbolic notation', keywords: ['⍺','⍵','←','∇','⍳','⍴','¨','∘.'], comment: { line: '⍝' }, indentStyle: 'none', features: ['array-primitives','tacit','rank','trains'] },
    { id: 'j',           name: 'J',           aliases: [],                      extensions: ['.ijs'],                     family: 'ml-scientific',  paradigms: ['array', 'functional'],                  typing: 'dynamic-strong',memory: 'gc',       year: 1990, popularity: 2, color: '#9EEDFF', description: 'Array programming language, descendant of APL',  keywords: ['NB.','monad','dyad','verb','noun','[.','].'], comment: { line: 'NB.' }, indentStyle: 'none', features: ['tacit','gerunds','rank','trains'] },

    // ── Functional ───────────────────────────────────────────────────────────
    { id: 'haskell',     name: 'Haskell',     aliases: ['hs'],                  extensions: ['.hs','.lhs'],               family: 'functional',    paradigms: ['functional'],                           typing: 'static-strong', memory: 'gc',       year: 1990, popularity: 6, color: '#5e5086', description: 'Pure functional language with lazy evaluation', keywords: ['module','import','data','class','instance','where','let','in','do','type'], comment: { line: '--', blockStart: '{-', blockEnd: '-}' }, indentStyle: 'indent', features: ['lazy','type-classes','monads','pattern-matching','algebraic-types','cabal'] },
    { id: 'ocaml',       name: 'OCaml',       aliases: ['ml'],                  extensions: ['.ml','.mli'],               family: 'functional',    paradigms: ['functional', 'imperative', 'oop'],      typing: 'inferred',      memory: 'gc',       year: 1996, popularity: 4, color: '#3be133', description: 'Pragmatic ML with objects and mutability',  keywords: ['let','rec','module','type','match','with','fun','open','val','sig','struct'], comment: { line: '(*', blockStart: '(*', blockEnd: '*)' }, indentStyle: 'indent', features: ['algebraic-types','functors','gadt','variants','dune'] },
    { id: 'fsharp',      name: 'F#',          aliases: ['fs'],                  extensions: ['.fs','.fsx','.fsi'],        family: 'functional',    paradigms: ['functional', 'imperative', 'oop'],      typing: 'inferred',      memory: 'gc',       year: 2005, popularity: 5, color: '#b845fc', description: 'Pragmatic functional language on .NET/CLR',  keywords: ['let','fun','match','with','open','module','type','member','interface'], comment: { line: '//', blockStart: '(*', blockEnd: '*)' }, indentStyle: 'indent', features: ['discriminated-unions','computation-expressions','type-providers','active-patterns'] },
    { id: 'elm',         name: 'Elm',         aliases: [],                      extensions: ['.elm'],                     family: 'functional',    paradigms: ['functional', 'reactive'],               typing: 'static-strong', memory: 'gc',       year: 2012, popularity: 4, color: '#60B5CC', description: 'Functional language for reliable web UIs',  keywords: ['module','import','type','let','in','case','of','|','exposing'], comment: { line: '--', blockStart: '{-', blockEnd: '-}' }, indentStyle: 'indent', features: ['no-runtime-errors','time-travel-debugger','model-view-update'] },
    { id: 'purescript',  name: 'PureScript',  aliases: ['ps'],                  extensions: ['.purs'],                    family: 'functional',    paradigms: ['functional'],                           typing: 'static-strong', memory: 'gc',       year: 2013, popularity: 3, color: '#1D222D', description: 'Strongly typed Haskell-like language compiling to JS', keywords: ['module','import','where','do','case','of','class','instance','data','type'], comment: { line: '--', blockStart: '{-', blockEnd: '-}' }, indentStyle: 'indent', features: ['row-polymorphism','effects','lens','halogen'] },
    { id: 'reasonml',    name: 'ReasonML',    aliases: ['reason','re'],         extensions: ['.re','.rei'],               family: 'functional',    paradigms: ['functional', 'oop'],                    typing: 'inferred',      memory: 'gc',       year: 2016, popularity: 3, color: '#ff5847', description: 'OCaml with JavaScript-friendly syntax',    keywords: ['let','fun','module','type','switch','external','[@bs.'],     comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['pattern-matching','variants','bucklescript'] },
    { id: 'idris',       name: 'Idris',       aliases: [],                      extensions: ['.idr'],                     family: 'functional',    paradigms: ['functional', 'declarative'],            typing: 'dependent',     memory: 'gc',       year: 2007, popularity: 2, color: '#b30000', description: 'Dependently typed functional programming language', keywords: ['module','import','data','where','interface','implementation','total','partial'], comment: { line: '--', blockStart: '{-', blockEnd: '-}' }, indentStyle: 'indent', features: ['dependent-types','totality','proofs','effects'] },
    { id: 'agda',        name: 'Agda',        aliases: [],                      extensions: ['.agda','.lagda'],           family: 'functional',    paradigms: ['functional', 'logic'],                  typing: 'dependent',     memory: 'gc',       year: 2007, popularity: 2, color: '#315665', description: 'Proof assistant and dependently typed language', keywords: ['module','open','import','data','record','where','Set','∀','→'], comment: { line: '--', blockStart: '{-', blockEnd: '-}' }, indentStyle: 'indent', features: ['dependent-types','universe-polymorphism','proof-checking'] },
    { id: 'coq',         name: 'Coq',         aliases: ['rocq','gallina'],      extensions: ['.v'],                       family: 'functional',    paradigms: ['functional', 'logic'],                  typing: 'dependent',     memory: 'gc',       year: 1989, popularity: 3, color: '#d0901f', description: 'Interactive theorem prover with dependent types', keywords: ['Theorem','Proof','Qed','Inductive','Fixpoint','Definition','Require Import'], comment: { line: '(*', blockStart: '(*', blockEnd: '*)' }, indentStyle: 'indent', features: ['tactics','proof-terms','extraction','ssreflect'] },
    { id: 'lean',        name: 'Lean',        aliases: ['lean4'],               extensions: ['.lean'],                    family: 'functional',    paradigms: ['functional', 'logic'],                  typing: 'dependent',     memory: 'gc',       year: 2013, popularity: 3, color: '#000000', description: 'Modern proof assistant and functional language', keywords: ['def','theorem','lemma','inductive','structure','class','instance','#check'], comment: { line: '--', blockStart: '/-', blockEnd: '-/' }, indentStyle: 'indent', features: ['dependent-types','tactics','mathlib','metaprogramming'] },
    { id: 'clojure',     name: 'Clojure',     aliases: ['clj'],                 extensions: ['.clj','.cljs','.cljc'],     family: 'lisp',          paradigms: ['functional', 'concurrent'],             typing: 'dynamic-strong',memory: 'gc',       year: 2007, popularity: 5, color: '#db5855', description: 'Lisp on the JVM with persistent data structures', keywords: ['defn','def','let','ns','require','cond','->','defmacro','atom'], comment: { line: ';' }, indentStyle: 'parentheses', features: ['immutability','stm','protocols','macros','transducers'] },
    { id: 'commonlisp',  name: 'Common Lisp', aliases: ['lisp','cl'],           extensions: ['.lisp','.cl'],              family: 'lisp',          paradigms: ['functional', 'oop', 'meta'],            typing: 'dynamic-strong',memory: 'gc',       year: 1984, popularity: 3, color: '#3fb68b', description: 'The most powerful and expressive Lisp dialect', keywords: ['defun','defvar','defmacro','let','cond','loop','format','progn'], comment: { line: ';', blockStart: '#|', blockEnd: '|#' }, indentStyle: 'parentheses', features: ['macros','clos','restarts','conditions','reader-macros'] },
    { id: 'scheme',      name: 'Scheme',      aliases: [],                      extensions: ['.scm','.ss'],               family: 'lisp',          paradigms: ['functional'],                           typing: 'dynamic-strong',memory: 'gc',       year: 1975, popularity: 3, color: '#1e4aec', description: 'Minimalist, elegant Lisp dialect',          keywords: ['define','lambda','let','cond','car','cdr','cons','begin'], comment: { line: ';' }, indentStyle: 'parentheses', features: ['tail-calls','continuations','hygienic-macros','r7rs'] },
    { id: 'racket',      name: 'Racket',      aliases: [],                      extensions: ['.rkt','.rktl'],             family: 'lisp',          paradigms: ['functional', 'imperative', 'oop'],      typing: 'gradual',       memory: 'gc',       year: 1994, popularity: 3, color: '#3c5caa', description: 'General-purpose programming language based on Scheme', keywords: ['#lang','define','lambda','module','require','provide','class*'], comment: { line: ';', blockStart: '#|', blockEnd: '|#' }, indentStyle: 'parentheses', features: ['macros','contracts','gui','typed-racket','drracket'] },
    { id: 'fennel',      name: 'Fennel',      aliases: [],                      extensions: ['.fnl'],                     family: 'lisp',          paradigms: ['functional', 'imperative'],             typing: 'dynamic-strong',memory: 'gc',       year: 2016, popularity: 2, color: '#fff3d7', description: 'Lisp for the Lua runtime',                  keywords: ['fn','local','let','if','when','match','require','lambda'], comment: { line: ';' }, indentStyle: 'parentheses', features: ['lua-interop','macros','pattern-matching'] },

    // ── Systems ───────────────────────────────────────────────────────────────
    { id: 'rust',        name: 'Rust',        aliases: ['rs'],                  extensions: ['.rs'],                      family: 'systems',       paradigms: ['imperative', 'functional', 'concurrent'], typing: 'static-strong', memory: 'ownership', year: 2010, popularity: 8, color: '#dea584', description: 'Systems language with memory safety without GC', keywords: ['fn','let','mut','pub','impl','trait','struct','enum','match','unwrap','cargo'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['ownership','lifetimes','traits','async','macros','cargo'] },
    { id: 'zig',         name: 'Zig',         aliases: [],                      extensions: ['.zig'],                     family: 'systems',       paradigms: ['imperative'],                           typing: 'static-strong', memory: 'manual',   year: 2016, popularity: 5, color: '#ec915c', description: 'Simple, fast, and safe systems language',   keywords: ['const','var','fn','pub','struct','enum','comptime','@import','try','unreachable'], comment: { line: '//' }, indentStyle: 'braces', features: ['comptime','no-hidden-allocations','c-interop','build-system'] },
    { id: 'odin',        name: 'Odin',        aliases: [],                      extensions: ['.odin'],                    family: 'systems',       paradigms: ['imperative'],                           typing: 'static-strong', memory: 'manual',   year: 2016, popularity: 3, color: '#60AFFE', description: 'Data-oriented systems language for game dev', keywords: ['package','import','proc','struct','union','distinct','when','foreign'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['soa','context-system','using','foreign','comptime'] },
    { id: 'wasm',        name: 'WebAssembly', aliases: ['wat','wasm'],          extensions: ['.wat','.wasm'],             family: 'systems',       paradigms: ['stack'],                                typing: 'static-strong', memory: 'manual',   year: 2017, popularity: 6, color: '#04133b', description: 'Binary instruction format for a stack-based VM', keywords: ['(module','(func','(import','(export','(memory','(table','i32.const'], comment: { line: ';;', blockStart: '(;', blockEnd: ';)' }, indentStyle: 'parentheses', features: ['portable','fast','sandboxed','multi-language-target'] },
    { id: 'asm-x86',     name: 'x86 Assembly',aliases: ['asm','nasm','masm'],  extensions: ['.asm','.s'],                family: 'systems',       paradigms: ['imperative', 'stack'],                  typing: 'none',          memory: 'manual',   year: 1978, popularity: 4, color: '#6E4C13', description: 'x86/x64 assembly language',                 keywords: ['mov','push','pop','call','ret','jmp','section .text','extern','global'], comment: { line: ';' }, indentStyle: 'none', features: ['registers','memory-access','syscalls','simd'] },
    { id: 'asm-arm',     name: 'ARM Assembly',aliases: ['arm-asm'],            extensions: ['.S'],                       family: 'systems',       paradigms: ['imperative', 'stack'],                  typing: 'none',          memory: 'manual',   year: 1985, popularity: 4, color: '#0091bd', description: 'ARM assembly language for embedded/mobile',  keywords: ['MOV','LDR','STR','BL','BX','PUSH','POP','AREA','ENTRY'], comment: { line: ';' }, indentStyle: 'none', features: ['thumb','neon','conditional-execution'] },
    { id: 'llvm-ir',     name: 'LLVM IR',     aliases: ['llvm'],               extensions: ['.ll'],                      family: 'systems',       paradigms: ['imperative', 'stack'],                  typing: 'static-strong', memory: 'manual',   year: 2003, popularity: 3, color: '#185619', description: 'LLVM intermediate representation',           keywords: ['define','declare','alloca','load','store','br','call','ret','getelementptr'], comment: { line: ';' }, indentStyle: 'none', features: ['ssa-form','optimizer','multi-target'] },

    // ── Shell ─────────────────────────────────────────────────────────────────
    { id: 'bash',        name: 'Bash',        aliases: ['sh','shell'],          extensions: ['.sh','.bash'],              family: 'shell',         paradigms: ['imperative'],                           typing: 'dynamic-weak',  memory: 'none',     year: 1989, popularity: 8, color: '#89e051', description: 'Bourne Again Shell scripting language',     keywords: ['#!/bin/bash','if','then','fi','for','do','done','echo','function','$()'], shebang: '#!/bin/bash', comment: { line: '#' }, indentStyle: 'indent', features: ['pipes','glob','process-substitution','arrays'] },
    { id: 'powershell',  name: 'PowerShell',  aliases: ['ps1','pwsh'],          extensions: ['.ps1','.psm1','.psd1'],     family: 'shell',         paradigms: ['imperative', 'oop'],                    typing: 'dynamic-strong',memory: 'gc',       year: 2006, popularity: 7, color: '#012456', description: 'Task automation and configuration management shell', keywords: ['function','param','$','Write-Host','Get-','Set-','Invoke-','-ErrorAction'], comment: { line: '#', blockStart: '<#', blockEnd: '#>' }, indentStyle: 'braces', features: ['cmdlets','pipeline','modules','dsc','remoting'] },
    { id: 'fish',        name: 'Fish',        aliases: [],                      extensions: ['.fish'],                    family: 'shell',         paradigms: ['imperative'],                           typing: 'dynamic-weak',  memory: 'none',     year: 2005, popularity: 4, color: '#4aae47', description: 'Friendly interactive shell',                keywords: ['function','end','if','else','for','in','while','and','or','not'], comment: { line: '#' }, indentStyle: 'indent', features: ['autosuggestions','no-sigils','universal-variables'] },
    { id: 'zsh',         name: 'Zsh',         aliases: [],                      extensions: ['.zsh'],                     family: 'shell',         paradigms: ['imperative'],                           typing: 'dynamic-weak',  memory: 'none',     year: 1990, popularity: 6, color: '#89e051', description: 'Extended Bourne shell with many improvements', keywords: ['#!/bin/zsh','autoload','setopt','zstyle','compinit','bindkey'], shebang: '#!/bin/zsh', comment: { line: '#' }, indentStyle: 'indent', features: ['completion','globbing','themes','oh-my-zsh'] },
    { id: 'batch',       name: 'Batch',       aliases: ['cmd','bat'],           extensions: ['.bat','.cmd'],              family: 'shell',         paradigms: ['imperative'],                           typing: 'none',          memory: 'none',     year: 1981, popularity: 4, color: '#C1F12E', description: 'Windows batch scripting language',           keywords: ['@echo off','echo','set','if','for','goto','call','rem','pause'], comment: { line: 'rem' }, indentStyle: 'none', features: ['environment-vars','labels','subroutines'] },
    { id: 'tcl',         name: 'Tcl',         aliases: ['tk'],                  extensions: ['.tcl','.tk'],               family: 'shell',         paradigms: ['imperative', 'event-driven'],            typing: 'dynamic-weak',  memory: 'gc',       year: 1988, popularity: 3, color: '#e4cc98', description: 'Tool Command Language, scripting and GUI',   keywords: ['proc','set','puts','if','foreach','lappend','namespace','package'], comment: { line: '#' }, indentStyle: 'indent', features: ['everything-is-string','extension-c','tk-gui','event-loop'] },
    { id: 'makefile',    name: 'Makefile',    aliases: ['make','gmake'],        extensions: ['.mk','Makefile'],           family: 'shell',         paradigms: ['declarative', 'imperative'],            typing: 'none',          memory: 'none',     year: 1976, popularity: 6, color: '#427819', description: 'Build automation tool rules file',          keywords: ['all:','.PHONY:','$(CC)','$(CFLAGS)','ifdef','ifndef','include','\t'], comment: { line: '#' }, indentStyle: 'none', features: ['targets','dependencies','variables','pattern-rules'] },

    // ── Data / Query ──────────────────────────────────────────────────────────
    { id: 'sql',         name: 'SQL',         aliases: ['mysql','postgres','sqlite'], extensions: ['.sql'],               family: 'data',          paradigms: ['declarative'],                          typing: 'static-strong', memory: 'none',     year: 1974, popularity: 9, color: '#e38c00', description: 'Structured Query Language for databases',   keywords: ['SELECT','FROM','WHERE','INSERT','UPDATE','DELETE','CREATE TABLE','JOIN'], comment: { line: '--', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'none', features: ['ddl','dml','transactions','views','procedures','indexes'] },
    { id: 'json',        name: 'JSON',        aliases: ['jsonc'],               extensions: ['.json','.jsonc'],           family: 'data',          paradigms: ['declarative'],                          typing: 'dynamic-strong',memory: 'none',     year: 2001, popularity: 10, color: '#292929', description: 'JavaScript Object Notation data format',   keywords: ['{','[','"key":','null','true','false'], comment: { line: '//' }, indentStyle: 'none', features: ['nested','arrays','objects','null-safe-in-spec'] },
    { id: 'yaml',        name: 'YAML',        aliases: ['yml'],                 extensions: ['.yaml','.yml'],             family: 'data',          paradigms: ['declarative'],                          typing: 'dynamic-strong',memory: 'none',     year: 2001, popularity: 9, color: '#cb171e', description: 'Human-friendly data serialization standard', keywords: ['---','key:','- ','|','>','!!','&','*'], comment: { line: '#' }, indentStyle: 'indent', features: ['anchors','aliases','multi-line','sequences'] },
    { id: 'toml',        name: 'TOML',        aliases: [],                      extensions: ['.toml'],                    family: 'data',          paradigms: ['declarative'],                          typing: 'static-strong', memory: 'none',     year: 2013, popularity: 7, color: '#9c4221', description: 'Tom\'s Obvious Minimal Language config format', keywords: ['[table]','[[array]]','key = ','[package]'], comment: { line: '#' }, indentStyle: 'none', features: ['typed','tables','arrays-of-tables'] },
    { id: 'xml',         name: 'XML',         aliases: ['xhtml','svg'],         extensions: ['.xml','.xml','.svg'],       family: 'data',          paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 1996, popularity: 7, color: '#0060ac', description: 'eXtensible Markup Language for structured data', keywords: ['<?xml','<root>','</','xmlns:','<!DOCTYPE','<![CDATA['], comment: { line: '<!--', blockStart: '<!--', blockEnd: '-->' }, indentStyle: 'none', features: ['namespaces','xsd','xslt','xpath','dtd'] },
    { id: 'graphql',     name: 'GraphQL',     aliases: ['gql'],                 extensions: ['.graphql','.gql'],          family: 'query',         paradigms: ['declarative'],                          typing: 'static-strong', memory: 'none',     year: 2015, popularity: 7, color: '#e10098', description: 'Query language for APIs and type system',   keywords: ['query','mutation','subscription','type','schema','input','fragment','interface'], comment: { line: '#' }, indentStyle: 'braces', features: ['strongly-typed','introspection','subscriptions','fragments'] },
    { id: 'sparql',      name: 'SPARQL',      aliases: [],                      extensions: ['.sparql','.rq'],            family: 'query',         paradigms: ['declarative', 'logic'],                 typing: 'none',          memory: 'none',     year: 2004, popularity: 3, color: '#0C4597', description: 'Query language for RDF data',               keywords: ['SELECT','WHERE','FILTER','OPTIONAL','PREFIX','GRAPH','UNION'], comment: { line: '#' }, indentStyle: 'indent', features: ['rdf','linked-data','federated-queries'] },
    { id: 'cypher',      name: 'Cypher',      aliases: ['neo4j-ql'],            extensions: ['.cyp','.cypher'],           family: 'query',         paradigms: ['declarative'],                          typing: 'dynamic-strong',memory: 'none',     year: 2011, popularity: 4, color: '#008CC1', description: 'Graph query language for Neo4j',            keywords: ['MATCH','WHERE','RETURN','CREATE','MERGE','WITH','DETACH DELETE'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'indent', features: ['graph-patterns','path-queries','aggregations'] },
    { id: 'hcl',         name: 'HCL',         aliases: ['terraform'],           extensions: ['.tf','.tfvars','.hcl'],     family: 'data',          paradigms: ['declarative'],                          typing: 'gradual',        memory: 'none',    year: 2014, popularity: 7, color: '#7B42BC', description: 'HashiCorp Configuration Language for IaC',  keywords: ['resource','variable','output','module','provider','data','locals','terraform'], comment: { line: '#', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['interpolation','expressions','modules','remote-state'] },
    { id: 'csv',         name: 'CSV',         aliases: ['tsv'],                 extensions: ['.csv','.tsv'],              family: 'data',          paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 1972, popularity: 8, color: '#237346', description: 'Comma-separated values tabular data format', keywords: [',','"header1,header2'], comment: { line: '' }, indentStyle: 'none', features: ['tabular','universal','simple'] },
    { id: 'protobuf',    name: 'Protocol Buffers',aliases: ['proto'],           extensions: ['.proto'],                   family: 'data',          paradigms: ['declarative'],                          typing: 'static-strong', memory: 'none',     year: 2008, popularity: 6, color: '#4885ed', description: 'Google\'s language-neutral serialization format', keywords: ['syntax = "proto','message','repeated','required','optional','enum','service','rpc'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['binary-format','grpc','schema-evolution','cross-language'] },

    // ── Web ───────────────────────────────────────────────────────────────────
    { id: 'html',        name: 'HTML',        aliases: ['html5'],               extensions: ['.html','.htm'],             family: 'web',           paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 1993, popularity: 10, color: '#e34c26', description: 'HyperText Markup Language, the backbone of the web', keywords: ['<!DOCTYPE html>','<html','<head','<body','<div','<script','<style','<a href'], comment: { line: '<!--', blockStart: '<!--', blockEnd: '-->' }, indentStyle: 'none', features: ['semantic','accessibility','forms','canvas','webcomponents'] },
    { id: 'css',         name: 'CSS',         aliases: ['css3'],                extensions: ['.css'],                     family: 'web',           paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 1996, popularity: 10, color: '#563d7c', description: 'Cascading Style Sheets for visual presentation', keywords: ['.class','{','margin:','padding:','color:','@media','var(--','display:','flex','grid'], comment: { line: '', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['variables','flexbox','grid','animations','custom-properties','container-queries'] },
    { id: 'scss',        name: 'SCSS',        aliases: ['sass'],                extensions: ['.scss','.sass'],            family: 'web',           paradigms: ['declarative', 'imperative'],            typing: 'none',          memory: 'none',     year: 2006, popularity: 7, color: '#c6538c', description: 'Sassy CSS preprocessor with nesting and variables', keywords: ['$variable','@mixin','@include','@extend','@import','@use','@forward','&:hover'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['nesting','mixins','functions','maps','modules'] },
    { id: 'less',        name: 'LESS',        aliases: [],                      extensions: ['.less'],                    family: 'web',           paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 2009, popularity: 5, color: '#1d365d', description: 'Leaner CSS preprocessor that extends CSS',  keywords: ['@variable:','#mixin()','&:','@import','.mixin;'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['variables','mixins','nesting','operations'] },
    { id: 'jsx',         name: 'JSX / React', aliases: ['react','tsx'],         extensions: ['.jsx','.tsx'],              family: 'web',           paradigms: ['declarative', 'functional', 'event-driven'], typing: 'gradual',    memory: 'gc',       year: 2013, popularity: 9, color: '#61dafb', description: 'React component syntax blending JS with XML', keywords: ['import React','useState','useEffect','<Component','<div className','Props','JSX'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['components','hooks','virtual-dom','context','suspense'] },
    { id: 'vue',         name: 'Vue',         aliases: ['vue3'],                extensions: ['.vue'],                     family: 'web',           paradigms: ['declarative', 'reactive', 'oop'],       typing: 'gradual',       memory: 'gc',       year: 2014, popularity: 8, color: '#42b883', description: 'Progressive JavaScript framework for UIs',   keywords: ['<template>','<script setup','<style scoped','defineProps','ref(','v-if','v-for','emit'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'mixed', features: ['composition-api','directives','reactivity','single-file-components','pinia'] },
    { id: 'svelte',      name: 'Svelte',      aliases: [],                      extensions: ['.svelte'],                  family: 'web',           paradigms: ['declarative', 'reactive'],              typing: 'gradual',       memory: 'gc',       year: 2016, popularity: 7, color: '#ff3e00', description: 'Compiled web framework — no virtual DOM',    keywords: ['<script>','$:','on:click','bind:','{#if','{#each','{#await','export let'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'mixed', features: ['compiled','stores','transitions','actions','sveltekit'] },
    { id: 'angular',     name: 'Angular',     aliases: ['ng'],                  extensions: ['.component.ts','.module.ts'], family: 'web',          paradigms: ['oop', 'declarative', 'reactive'],       typing: 'static-strong', memory: 'gc',       year: 2016, popularity: 7, color: '#dd0031', description: 'Google\'s full-featured front-end framework', keywords: ['@Component','@NgModule','@Injectable','@Input','@Output','ngFor','ngIf','Observable'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['dependency-injection','rxjs','signals','standalone-components','zoneless'] },
    { id: 'astro',       name: 'Astro',       aliases: [],                      extensions: ['.astro'],                   family: 'web',           paradigms: ['declarative', 'functional'],            typing: 'gradual',       memory: 'gc',       year: 2021, popularity: 5, color: '#ff5d01', description: 'Islands architecture static site framework', keywords: ['---','Astro.props','<Layout','getStaticPaths','import','astro:content'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'mixed', features: ['islands','content-collections','partial-hydration','server-islands'] },
    { id: 'solidjs',     name: 'SolidJS',     aliases: ['solid'],               extensions: ['.jsx','.tsx'],              family: 'web',           paradigms: ['functional', 'reactive'],               typing: 'gradual',       memory: 'gc',       year: 2018, popularity: 5, color: '#2c4f7c', description: 'Declarative, efficient, fine-grained reactive UI', keywords: ['createSignal','createEffect','createMemo','Show','For','createResource','<Dynamic'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['fine-grained-reactivity','no-vdom','signals','stores','server-components'] },
    { id: 'handlebars',  name: 'Handlebars',  aliases: ['hbs','mustache'],      extensions: ['.hbs','.handlebars','.mustache'], family: 'template', paradigms: ['declarative'],                        typing: 'none',          memory: 'none',     year: 2010, popularity: 5, color: '#f7931e', description: 'Logic-less template language',              keywords: ['{{','}}','{{#if','{{#each','{{>','{{!--','{{else}}'], comment: { line: '{{!--', blockStart: '{{!--', blockEnd: '--}}' }, indentStyle: 'none', features: ['partials','helpers','contexts'] },
    { id: 'jinja',       name: 'Jinja',       aliases: ['jinja2'],              extensions: ['.j2','.jinja','.jinja2'],   family: 'template',      paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 2008, popularity: 6, color: '#b41717', description: 'Python templating engine',                  keywords: ['{%','%}','{{','}}','{# #}','{% extends','{% block','{% for','{% if'], comment: { line: '{#', blockStart: '{#', blockEnd: '#}' }, indentStyle: 'indent', features: ['inheritance','filters','macros','tests'] },

    // ── Concurrent / Actor ────────────────────────────────────────────────────
    { id: 'erlang',      name: 'Erlang',      aliases: [],                      extensions: ['.erl','.hrl'],              family: 'concurrent',    paradigms: ['functional', 'concurrent'],             typing: 'dynamic-strong',memory: 'gc',       year: 1986, popularity: 4, color: '#B83998', description: 'Telecom-grade concurrent functional language', keywords: ['-module(','-export','spawn','receive','!','gen_server','supervisor'], comment: { line: '%' }, indentStyle: 'indent', features: ['actors','hot-code-reloading','otp','distribution','supervision-trees'] },
    { id: 'pony',        name: 'Pony',        aliases: [],                      extensions: ['.pony'],                    family: 'concurrent',    paradigms: ['oop', 'concurrent'],                    typing: 'static-strong', memory: 'gc',       year: 2014, popularity: 2, color: '#ffffff', description: 'Actor-model OOP language with capabilities',  keywords: ['actor','class','interface','trait','primitive','new','be','fun','recover','consume'], comment: { line: '//' }, indentStyle: 'indent', features: ['capabilities','actors','no-data-races','zero-copy-message-passing'] },

    // ── Logic ─────────────────────────────────────────────────────────────────
    { id: 'prolog',      name: 'Prolog',      aliases: ['swiprolog'],           extensions: ['.pl','.pro','.prolog'],     family: 'logic',         paradigms: ['logic', 'declarative'],                 typing: 'dynamic-strong',memory: 'gc',       year: 1972, popularity: 3, color: '#74283c', description: 'Logic programming language',                 keywords: [':-','assert','retract','functor','clause','?-','not','findall'], comment: { line: '%' }, indentStyle: 'none', features: ['unification','backtracking','constraints','dcg','tabling'] },
    { id: 'datalog',     name: 'Datalog',     aliases: [],                      extensions: ['.dl'],                      family: 'logic',         paradigms: ['logic', 'declarative'],                 typing: 'static-strong', memory: 'none',     year: 1977, popularity: 2, color: '#3c4a6e', description: 'Declarative subset of Prolog for querying',   keywords: ['.decl',':-','output','input','type','number_of'], comment: { line: '//' }, indentStyle: 'none', features: ['fixed-point-semantics','stratified-negation','incremental'] },

    // ── Legacy ────────────────────────────────────────────────────────────────
    { id: 'cobol',       name: 'COBOL',       aliases: [],                      extensions: ['.cob','.cbl','.cobol'],     family: 'legacy',        paradigms: ['imperative'],                           typing: 'static-strong', memory: 'manual',   year: 1959, popularity: 4, color: '#1d6b31', description: 'Business-oriented language still powering banking', keywords: ['IDENTIFICATION DIVISION','PROGRAM-ID','DATA DIVISION','PROCEDURE DIVISION','PERFORM','MOVE'], comment: { line: '*>' }, indentStyle: 'none', features: ['fixed-format','divisions','pictures','fileid'] },
    { id: 'fortran',     name: 'Fortran',     aliases: ['f90','f95'],           extensions: ['.f90','.f95','.f03','.f'], family: 'legacy',        paradigms: ['imperative', 'array'],                  typing: 'static-strong', memory: 'manual',   year: 1957, popularity: 4, color: '#4d41b1', description: 'Scientific computing language still widely used', keywords: ['PROGRAM','SUBROUTINE','FUNCTION','IMPLICIT NONE','INTEGER','REAL','DO','ENDDO'], comment: { line: '!' }, indentStyle: 'indent', features: ['arrays','modules','openmp','coarrays'] },
    { id: 'basic',       name: 'BASIC',       aliases: ['vb','visual-basic'],   extensions: ['.bas','.vb'],               family: 'legacy',        paradigms: ['imperative'],                           typing: 'dynamic-weak',  memory: 'gc',       year: 1964, popularity: 3, color: '#945db7', description: 'Beginner\'s All-purpose Symbolic Instruction Code', keywords: ['DIM','LET','PRINT','INPUT','GOTO','IF...THEN','FOR...NEXT','SUB','END'], comment: { line: '\'' }, indentStyle: 'indent', features: ['line-numbers','goto','dialects'] },
    { id: 'pascal',      name: 'Pascal',      aliases: ['delphi','oberon'],     extensions: ['.pas','.pp'],               family: 'legacy',        paradigms: ['imperative', 'oop'],                    typing: 'static-strong', memory: 'manual',   year: 1970, popularity: 3, color: '#E3F171', description: 'Teaching language that influenced modern languages', keywords: ['program','begin','end','var','procedure','function','type','record'], comment: { line: '//', blockStart: '(*', blockEnd: '*)' }, indentStyle: 'begin-end', features: ['strong-typing','structured','units'] },
    { id: 'ada',         name: 'Ada',         aliases: ['ada2012'],             extensions: ['.adb','.ads'],              family: 'legacy',        paradigms: ['imperative', 'concurrent', 'oop'],     typing: 'static-strong', memory: 'gc',       year: 1980, popularity: 3, color: '#02f88c', description: 'Safety-critical systems language used in aerospace/defense', keywords: ['procedure','function','package','with','use','begin','end','type','task'], comment: { line: '--' }, indentStyle: 'begin-end', features: ['tasking','contracts','generics','spark-subset'] },

    // ── Omni Languages ────────────────────────────────────────────────────────
    { id: 'titan',       name: 'Titan',       aliases: [],                      extensions: ['.titan','.ti'],             family: 'omni',          paradigms: ['imperative', 'functional', 'concurrent'], typing: 'static-strong', memory: 'ownership', year: 2024, popularity: 5, color: '#00D4FF', description: 'Omnisystem\'s primary systems language — Rust-inspired with actor model', keywords: ['pub fn','pub struct','impl','actor','let','mut','mod','use crate::'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['ownership','actors','macros','zero-cost','ffi'] },
    { id: 'vera',        name: 'Vera',        aliases: [],                      extensions: ['.vera'],                    family: 'omni',          paradigms: ['declarative', 'functional', 'reactive'], typing: 'static-strong', memory: 'gc',       year: 2024, popularity: 5, color: '#7C3AED', description: 'Omnisystem\'s UI component language with OW theme integration', keywords: ['component','props','state','render','event','style','@bind','@emit'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['components','reactivity','ow-themes','signals'] },
    { id: 'nexus',       name: 'Nexus',       aliases: [],                      extensions: ['.nexus'],                   family: 'omni',          paradigms: ['declarative'],                          typing: 'static-strong', memory: 'gc',       year: 2024, popularity: 4, color: '#10B981', description: 'Omnisystem\'s responsive layout language with constraint solver', keywords: ['layout','breakpoints','flex','grid','align','gap','responsive'], comment: { line: '//' }, indentStyle: 'braces', features: ['responsive','constraint-solver','ow-integration'] },
    { id: 'helix',       name: 'Helix',       aliases: [],                      extensions: ['.helix'],                   family: 'omni',          paradigms: ['declarative', 'dataflow'],              typing: 'static-strong', memory: 'manual',   year: 2024, popularity: 4, color: '#F59E0B', description: 'Omnisystem\'s GPU shader and pipeline language', keywords: ['shader','pipeline','vertex','fragment','uniform','sampler','#[target('], comment: { line: '//' }, indentStyle: 'braces', features: ['vulkan','dx12','metal','compute-shaders','pbr'] },
    { id: 'aether',      name: 'Aether',      aliases: [],                      extensions: ['.aether'],                  family: 'omni',          paradigms: ['concurrent', 'functional'],             typing: 'static-strong', memory: 'gc',       year: 2024, popularity: 4, color: '#06B6D4', description: 'Omnisystem\'s actor-model distributed computing language', keywords: ['actor','message','handler','spawn','mailbox','send','receive'], comment: { line: '//' }, indentStyle: 'braces', features: ['actors','distribution','supervision','hot-reload'] },
    { id: 'axiom',       name: 'Axiom',       aliases: [],                      extensions: ['.axiom'],                   family: 'omni',          paradigms: ['logic', 'functional'],                  typing: 'dependent',     memory: 'gc',       year: 2024, popularity: 3, color: '#EF4444', description: 'Omnisystem\'s formal verification and theorem proving language', keywords: ['theorem','preconditions','postconditions','invariants','assertions','proof'], comment: { line: '//' }, indentStyle: 'braces', features: ['smt-z3','invariants','proofs','contracts'] },
    { id: 'sylva',       name: 'Sylva',       aliases: [],                      extensions: ['.sylva'],                   family: 'omni',          paradigms: ['declarative', 'functional'],             typing: 'inferred',      memory: 'gc',       year: 2024, popularity: 4, color: '#84CC16', description: 'Omnisystem\'s machine learning framework language', keywords: ['layer','model','architecture','train','loss','optimizer','epoch'], comment: { line: '//' }, indentStyle: 'braces', features: ['autograd','blas-dispatch','neural-nets','sylva-runtime'] },

    // ── More languages to reach 250+ ──────────────────────────────────────────
    { id: 'vlang',       name: 'V',           aliases: ['vlang'],               extensions: ['.v'],                       family: 'c-family',      paradigms: ['imperative', 'oop'],                    typing: 'static-strong', memory: 'manual',   year: 2019, popularity: 4, color: '#5d87bf', description: 'Simple, fast, safe compiled language',       keywords: ['fn','mut','struct','pub','module','import','println','if err != none'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['no-null','no-gc','c-interop','vet'] },
    { id: 'ballerina',   name: 'Ballerina',   aliases: [],                      extensions: ['.bal'],                     family: 'c-family',      paradigms: ['oop', 'concurrent'],                    typing: 'static-strong', memory: 'gc',       year: 2017, popularity: 3, color: '#20b6b0', description: 'Cloud-native integration language',          keywords: ['import ballerina','function','service','resource','worker','transaction'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['network-types','services','workers','data-binding'] },
    { id: 'gleam',       name: 'Gleam',       aliases: [],                      extensions: ['.gleam'],                   family: 'functional',    paradigms: ['functional'],                           typing: 'static-strong', memory: 'gc',       year: 2019, popularity: 3, color: '#ffaff3', description: 'Type-safe, friendly functional language on Erlang VM', keywords: ['pub fn','let','use','case','import','type','pub type'], comment: { line: '//' }, indentStyle: 'braces', features: ['pattern-matching','no-exceptions','erlang-interop'] },
    { id: 'grain',       name: 'Grain',       aliases: [],                      extensions: ['.gr'],                      family: 'functional',    paradigms: ['functional'],                           typing: 'static-strong', memory: 'gc',       year: 2019, popularity: 2, color: '#fbdf00', description: 'Strongly-typed functional language compiling to WASM', keywords: ['module','import','let','match','record','enum','provide'], comment: { line: '//' }, indentStyle: 'braces', features: ['wasm','modules','records','pattern-matching'] },
    { id: 'koka',        name: 'Koka',        aliases: [],                      extensions: ['.kk'],                      family: 'functional',    paradigms: ['functional'],                           typing: 'inferred',      memory: 'gc',       year: 2012, popularity: 2, color: '#aaaaaa', description: 'Functional language with algebraic effects',  keywords: ['fun','val','effect','handle','return','except'], comment: { line: '//' }, indentStyle: 'indent', features: ['algebraic-effects','handlers','tail-recursion-modulo-cons'] },
    { id: 'roc',         name: 'Roc',         aliases: [],                      extensions: ['.roc'],                     family: 'functional',    paradigms: ['functional'],                           typing: 'inferred',      memory: 'gc',       year: 2021, popularity: 2, color: '#7c38f5', description: 'Fast, friendly, functional programming',     keywords: ['app','imports','main =','when','is','if','then','else'], comment: { line: '#' }, indentStyle: 'indent', features: ['no-runtime-exceptions','platform-agnostic','fast'] },
    { id: 'mojo',        name: 'Mojo',        aliases: [],                      extensions: ['.mojo','.🔥'],               family: 'python-family', paradigms: ['imperative', 'functional'],             typing: 'gradual',       memory: 'manual',   year: 2023, popularity: 5, color: '#ff6a00', description: 'Superset of Python for AI/HPC with systems-level control', keywords: ['fn','def','struct','alias','let','borrowed','inout','__mlir'], comment: { line: '#' }, indentStyle: 'indent', features: ['simd','mlir','ownership','zero-cost','python-superset'] },
    { id: 'solidity',    name: 'Solidity',    aliases: [],                      extensions: ['.sol'],                     family: 'c-family',      paradigms: ['oop', 'imperative'],                    typing: 'static-strong', memory: 'manual',   year: 2014, popularity: 5, color: '#AA6746', description: 'Smart contract language for Ethereum blockchain', keywords: ['pragma solidity','contract','function','modifier','event','emit','mapping','payable'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['abi','evm','gas','events','interfaces'] },
    { id: 'move',        name: 'Move',        aliases: [],                      extensions: ['.move'],                    family: 'functional',    paradigms: ['functional', 'imperative'],             typing: 'static-strong', memory: 'ownership', year: 2020, popularity: 3, color: '#4da6ff', description: 'Resource-oriented language for blockchain',   keywords: ['module','script','use','fun','struct','resource','move','copy','borrow'], comment: { line: '//' }, indentStyle: 'braces', features: ['linear-types','resources','verification','sui','aptos'] },
    { id: 'cairo',       name: 'Cairo',       aliases: [],                      extensions: ['.cairo'],                   family: 'systems',       paradigms: ['imperative', 'functional'],             typing: 'static-strong', memory: 'manual',   year: 2021, popularity: 3, color: '#ff6b6b', description: 'Rust-like language for STARK-based provable programs', keywords: ['fn','struct','enum','let','felt252','trait','impl','#[derive'], comment: { line: '//' }, indentStyle: 'braces', features: ['starks','provability','no-loops','starknet'] },
    { id: 'wgsl',        name: 'WGSL',        aliases: [],                      extensions: ['.wgsl'],                    family: 'systems',       paradigms: ['declarative', 'imperative'],            typing: 'static-strong', memory: 'none',     year: 2021, popularity: 3, color: '#0000aa', description: 'WebGPU Shading Language',                    keywords: ['@vertex','@fragment','@compute','fn','var','let','struct','binding'], comment: { line: '//' }, indentStyle: 'braces', features: ['webgpu','cross-platform-shaders','compute'] },
    { id: 'glsl',        name: 'GLSL',        aliases: ['hlsl','spirv'],        extensions: ['.glsl','.vert','.frag'],    family: 'systems',       paradigms: ['declarative', 'imperative'],            typing: 'static-strong', memory: 'none',     year: 2004, popularity: 5, color: '#5586a4', description: 'OpenGL Shading Language for GPU programs',   keywords: ['void main()','uniform','varying','attribute','gl_Position','texture2D','vec4'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'braces', features: ['gpu','vertex-shaders','fragment-shaders','compute'] },
    { id: 'forth',       name: 'Forth',       aliases: [],                      extensions: ['.forth','.fth'],            family: 'legacy',        paradigms: ['imperative', 'stack'],                  typing: 'none',          memory: 'manual',   year: 1970, popularity: 2, color: '#341708', description: 'Stack-based, concatenative systems language', keywords: [': word','.',' ok',' emit',' if',' then',' do',' loop'], comment: { line: '\\' }, indentStyle: 'none', features: ['stack','extensible','factor','concatenative'] },
    { id: 'factor',      name: 'Factor',      aliases: [],                      extensions: ['.factor'],                  family: 'legacy',        paradigms: ['functional', 'stack', 'oop'],           typing: 'dynamic-strong',memory: 'gc',       year: 2003, popularity: 2, color: '#636746', description: 'Modern concatenative/stack-based language',  keywords: ['USING:','IN:',': word','call','if','map','filter','compose'], comment: { line: '!' }, indentStyle: 'none', features: ['stack','quotations','words','vocabularies'] },
    { id: 'smalltalk',   name: 'Smalltalk',   aliases: ['pharo','squeak'],      extensions: ['.st'],                      family: 'python-family', paradigms: ['oop', 'event-driven'],                  typing: 'dynamic-strong',memory: 'gc',       year: 1972, popularity: 3, color: '#596706', description: 'The original OOP language — everything is an object', keywords: ['class','methodsFor:','ifTrue:','ifFalse:','whileTrue:','yourself','thisContext'], comment: { line: '"', blockStart: '"', blockEnd: '"' }, indentStyle: 'indent', features: ['image-based','message-passing','blocks','live-programming'] },
    { id: 'io',          name: 'Io',          aliases: [],                      extensions: ['.io'],                      family: 'python-family', paradigms: ['oop', 'concurrent'],                    typing: 'dynamic-strong',memory: 'gc',       year: 2002, popularity: 2, color: '#a9188d', description: 'Prototype-based, concurrent language inspired by Smalltalk/Self', keywords: ['Object clone','method','do','coroutine','send','yield'], comment: { line: '//', blockStart: '/*', blockEnd: '*/' }, indentStyle: 'indent', features: ['prototypes','coroutines','actors','message-passing'] },
    { id: 'self',        name: 'Self',        aliases: [],                      extensions: ['.self'],                    family: 'python-family', paradigms: ['oop'],                                  typing: 'dynamic-strong',memory: 'gc',       year: 1987, popularity: 1, color: '#0579aa', description: 'Prototype-based OOP language, ancestor of JavaScript prototypes', keywords: ['clone','parent','|','lobby','self'], comment: { line: '"' }, indentStyle: 'indent', features: ['prototypes','slots','morphic'] },
    { id: 'brainfuck',   name: 'Brainfuck',   aliases: ['bf'],                  extensions: ['.bf','.b'],                 family: 'esoteric',      paradigms: ['imperative', 'stack'],                  typing: 'none',          memory: 'manual',   year: 1993, popularity: 1, color: '#2f2530', description: 'Minimalist esoteric language with 8 commands', keywords: ['[',']','>','<','+','-','.', ','], comment: { line: '' }, indentStyle: 'none', features: ['turing-complete','8-commands','tape-memory'] },
    { id: 'whitespace',  name: 'Whitespace',  aliases: [],                      extensions: ['.ws'],                      family: 'esoteric',      paradigms: ['imperative', 'stack'],                  typing: 'none',          memory: 'manual',   year: 2003, popularity: 1, color: '#ffffff', description: 'Language using only spaces, tabs, and newlines', keywords: [' ','\t','\n'], comment: { line: '' }, indentStyle: 'none', features: ['whitespace-only','stack-based','turing-complete'] },
    { id: 'markdown',    name: 'Markdown',    aliases: ['md'],                  extensions: ['.md','.markdown'],          family: 'data',          paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 2004, popularity: 9, color: '#083fa1', description: 'Lightweight markup language for formatted text', keywords: ['#','##','**','*','```','> ','- ','[',']('], comment: { line: '' }, indentStyle: 'none', features: ['headers','lists','code','tables','links'] },
    { id: 'latex',       name: 'LaTeX',       aliases: ['tex'],                 extensions: ['.tex','.latex'],            family: 'template',      paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 1983, popularity: 6, color: '#008080', description: 'Document preparation system for scientific publishing', keywords: ['\\documentclass','\\begin{document}','\\section','\\usepackage','\\ref','$','$$'], comment: { line: '%' }, indentStyle: 'indent', features: ['math','bibliography','crossref','packages'] },
    { id: 'regex',       name: 'Regex',       aliases: ['regexp','pcre'],       extensions: ['.regex'],                   family: 'data',          paradigms: ['declarative'],                          typing: 'none',          memory: 'none',     year: 1951, popularity: 8, color: '#ff6600', description: 'Regular expression pattern matching language',  keywords: ['^','$','.','*','+','?','[',']','(',')','|','\\d','\\w','\\s'], comment: { line: '' }, indentStyle: 'none', features: ['patterns','groups','lookahead','lookbehind','backreferences'] },
];

// ─── Lookup structures built at module load ───────────────────────────────────

const BY_ID   = new Map<string, LanguageDef>();
const BY_EXT  = new Map<string, LanguageDef>();
const BY_NAME = new Map<string, LanguageDef>();  // lowercased
const BY_FAM  = new Map<LanguageFamily, LanguageDef[]>();

for (const lang of LANGUAGES) {
    BY_ID.set(lang.id, lang);
    BY_NAME.set(lang.name.toLowerCase(), lang);
    for (const alias of lang.aliases) { BY_NAME.set(alias.toLowerCase(), lang); }
    for (const ext of lang.extensions)  { BY_EXT.set(ext.toLowerCase(), lang); }
    if (!BY_FAM.has(lang.family)) { BY_FAM.set(lang.family, []); }
    BY_FAM.get(lang.family)!.push(lang);
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function getLang(id: string): LanguageDef | undefined {
    return BY_ID.get(id) ?? BY_NAME.get(id.toLowerCase());
}

export function getLangByExtension(ext: string): LanguageDef | undefined {
    // Most entries key on a dotted extension ('.py'), but a few special
    // filenames are stored bare ('Makefile', matched against a full
    // filename rather than a suffix) — try the dotted form first, then
    // fall back to the raw lowercased input so those still resolve.
    const lower = ext.toLowerCase();
    const dotted = ext.startsWith('.') ? lower : '.' + lower;
    return BY_EXT.get(dotted) ?? BY_EXT.get(lower);
}

export function getLangsByFamily(family: LanguageFamily): LanguageDef[] {
    return BY_FAM.get(family) ?? [];
}

export function allLanguages(): LanguageDef[] {
    return LANGUAGES;
}

export function searchLanguages(query: string): LanguageDef[] {
    const q = query.toLowerCase().trim();
    if (!q) { return LANGUAGES; }
    return LANGUAGES.filter(l =>
        l.id.includes(q) ||
        l.name.toLowerCase().includes(q) ||
        l.aliases.some(a => a.toLowerCase().includes(q)) ||
        l.description.toLowerCase().includes(q) ||
        l.extensions.some(e => e.includes(q)) ||
        l.family.includes(q)
    );
}

export function popularLanguages(limit = 30): LanguageDef[] {
    return [...LANGUAGES].sort((a, b) => b.popularity - a.popularity).slice(0, limit);
}

export function getConversionLabel(sourceId: string, targetId: string): string {
    const s = getLang(sourceId);
    const t = getLang(targetId);
    if (!s || !t) { return `${sourceId} → ${targetId}`; }
    return `${s.name} → ${t.name}`;
}

export function getFileExtension(langId: string): string {
    const lang = getLang(langId);
    return lang?.extensions[0] ?? '.txt';
}

export { LANGUAGES };
