[package]
name = "docker-container-lifecycle"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "docker_container_lifecycle"
path = "src/lib.rs"

[[bin]]
name = "docker_container_lifecycle_cli"
path = "src/bin/cli.rs"
test = false



