[package]
name = "docker-compose-advanced"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "docker_compose_advanced"
path = "src/lib.rs"

[[bin]]
name = "docker_compose_advanced_cli"
path = "src/bin/cli.rs"
test = false



