[package]
name = "form-components"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "form_components"
path = "src/lib.rs"

[[bin]]
name = "form_components_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
