[package]
name = "dockerfile-optimizer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "dockerfile_optimizer"
path = "src/lib.rs"

[[bin]]
name = "dockerfile_optimizer_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


