[package]
name = "agent-control-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "agent_control_ui"
path = "src/lib.rs"

[[bin]]
name = "agent_control_ui_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]
