[package]
name = "volume-management-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "volume_management_ui"
path = "src/lib.rs"

[[bin]]
name = "volume_management_ui_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]
