[package]
name = "container-security-platform"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lib]
name = "container_security_platform"
path = "src/lib.rs"

[[bin]]
name = "container_security_platform_cli"
path = "src/bin/cli.rs"
test = false



