[package]
name = "disaster-recovery-platform"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "disaster_recovery_platform"
path = "src/lib.rs"

[[bin]]
name = "disaster_recovery_platform_cli"
path = "src/bin/cli.rs"



