[package]
name = "form-builder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "form_builder"
path = "src/lib.rs"

[[bin]]
name = "form_builder_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]
