[package]
name = "global-failover"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }

[lib]
name = "global_failover"
path = "src/lib.rs"

[[bin]]
name = "global_failover_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


