[package]
name = "settings-configuration-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "settings_configuration_ui"
path = "src/lib.rs"

[[bin]]
name = "settings_configuration_ui_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]
