[package]
name = "animation-library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "animation_library"
path = "src/lib.rs"

[[bin]]
name = "animation_library_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
