[package]
name = "compliance-framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lib]
name = "compliance_framework"
path = "src/lib.rs"

[[bin]]
name = "compliance_framework_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


