[package]
name = "rbac-authorization-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lib]
name = "rbac_authorization_engine"
path = "src/lib.rs"

[[bin]]
name = "rbac_authorization_engine_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


