[package]
name = "security-analyzer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lib]
name = "security_analyzer"
path = "src/lib.rs"

[[bin]]
name = "security_analyzer_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]


